<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426124832 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE utilisateur_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE etudiant_id_seq CASCADE');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, date_de_naissance DATE NOT NULL, img_url VARCHAR(255) NOT NULL, section_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B723AF33D823E37A ON student (section_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33D823E37A FOREIGN KEY (section_id) REFERENCES section (id)');
        $this->addSql('ALTER TABLE etudiant DROP CONSTRAINT etudiant_section_id_fkey');
        $this->addSql('DROP TABLE etudiant');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP INDEX section_designation_key');
        $this->addSql('ALTER TABLE section ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE section ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE utilisateur_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE etudiant_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE etudiant (id INT DEFAULT nextval(\'etudiant_id_seq\'::regclass) NOT NULL, name VARCHAR(100) NOT NULL, date_de_naissance DATE NOT NULL, img_url VARCHAR(256) NOT NULL, section_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_717E22E3D823E37A ON etudiant (section_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT DEFAULT nextval(\'utilisateur_id_seq\'::regclass) NOT NULL, username VARCHAR(100) NOT NULL, password TEXT NOT NULL, role VARCHAR DEFAULT \'normal\', PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX utilisateur_username_key ON utilisateur (username)');
        $this->addSql('ALTER TABLE etudiant ADD CONSTRAINT etudiant_section_id_fkey FOREIGN KEY (section_id) REFERENCES section (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33D823E37A');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE section ALTER id SET DEFAULT nextval(\'section_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE section ALTER id DROP IDENTITY');
        $this->addSql('CREATE UNIQUE INDEX section_designation_key ON section (designation)');
    }
}
